#pragma once
#include <opencv2/core.hpp>
#include <string>

namespace lpr {

struct PlateResult {
    std::string     text;            // recognized plate string
    float           confidence = 0.f;
    cv::RotatedRect box;             // location in the source frame
    cv::Mat         plateImage;      // cropped plate
    long            timestamp = 0;
    std::string     gate;
    int             trackId = -1;    // vehicle track id (when produced via tracking), else -1
    cv::Rect        vehicleBox;      // owning vehicle box in the source frame (if any)
    // 0 unknown, 1 approaching (plate growing), 2 receding (shrinking). This is the
    // PHYSICAL size-trend; the backend maps it to entry/exit per camera
    // (approaching_is_entry). The module no longer applies Entry/Exit polarity.
    int             direction = 0;
    // Stable per-pass id (a UUID generated by DetectionWorker for each vehicle pass,
    // no tracking model needed). Sent as `plate.track_id` on the early event AND the
    // later direction-correction so the backend can update the same passage row.
    std::string     passId;
};

} // namespace lpr
